name: Pytests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PIPENV_VENV_IN_PROJECT: enabled

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: ./.venv # since we know that .venv is gonna be created in the current working directory
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup Environment
      run: |
        pipenv install --dev --verbose
    - name: Test with pytest
      run: |
        pipenv run pytest